export enum Role {
  ADMIN = 'ADMIN',
  COMMISSIONER = 'COMMISSIONER',
  JOINT_COMMISSIONER = 'JOINT_COMMISSIONER',
  DCP = 'DCP',
  ACP = 'ACP',
  INSPECTOR = 'INSPECTOR',
  SUB_INSPECTOR = 'SUB_INSPECTOR',
}
