import { Officer } from '../../officers/entities/officer.entity';
import { Role } from '../../officers/enums/role.enum';
import { Zone } from '../../officers/enums/zone.enum';
import { SubDivision } from '../../officers/enums/sub-division.enum';

export const officersSeedData: Partial<Officer>[] = [
  // === L&O Wing ===
  {
    name: "Dr. Shankhabrata Bagchi, IPS",
    username: "COMM",
    mobileNumber: "9440627277",
    password: "9440627277",
    role: Role.COMMISSIONER,
    designation: "Commissioner of Police",
    isActive: true,
  },
  {
    name: "Sri.",
    username: "JCP",
    mobileNumber: "9490624773",
    password: "9490624773",
    role: Role.JOINT_COMMISSIONER,
    designation: "Joint Commissioner of Police",
    isActive: true,
  },
  {
    name: "Sri. V.N.Ch.Manikanta, IPS",
    username: "DCP_ZONE1",
    mobileNumber: "9440904348",
    password: "9440904348",
    role: Role.DCP,
    zone: Zone.ZONE_1,
    designation: "D.C.P - L&O - I",
    isActive: true,
  },
  {
    name: "Sri . K.Laxmana Murthy",
    username: "ACP_EAST",
    mobileNumber: "9440796005",
    password: "9440796005",
    role: Role.ACP,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    designation: "ACP - East",
    isActive: true,
  },
  {
    name: "Sri. V.V.CM.Yerram Naidu",
    username: "INSP_IITOWN",
    mobileNumber: "9440904716",
    password: "9440904716",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "II Town",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri.G.Divkar Yadav",
    username: "INSP_MR-PETA",
    mobileNumber: "9440796010",
    password: "9440796010",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "MR-Peta",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. P.Pydayya",
    username: "INSP_IIITOWN",
    mobileNumber: "9440796011",
    password: "9440796011",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "III Town",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. CH.Umakanth",
    username: "INSP_IVTOWN",
    mobileNumber: "9440796012",
    password: "9440796012",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "IV Town",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. A.Narsimha Murthy",
    username: "ACP_DWARAKA",
    mobileNumber: "8331041655",
    password: "8331041655",
    role: Role.ACP,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    designation: "ACP - Dwaraka",
    isActive: true,
  },
  {
    name: "Sri. D.V.Ramana",
    username: "INSP_DWARAKA",
    mobileNumber: "9440904332",
    password: "9440904332",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "Dwaraka",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri.K.N.S.V.Prasad",
    username: "INSP_MVP",
    mobileNumber: "9490624746",
    password: "9490624746",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "MVP",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri.H.Malleswara Rao",
    username: "INSP_ARILOVA",
    mobileNumber: "9490617918",
    password: "9490617918",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "Arilova",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. S.Appalaraju",
    username: "ACP_NORTH",
    mobileNumber: "9490623962",
    password: "9490623962",
    role: Role.ACP,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    designation: "ACP - North",
    isActive: true,
  },
  {
    name: "Sri .G.Bala Krishna",
    username: "INSP_PMPALEM",
    mobileNumber: "9440796060",
    password: "9440796060",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "PM Palem",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri B.Tirumala Rao",
    username: "INSP_BHEEMILI",
    mobileNumber: "9440904712",
    password: "9440904712",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "Bheemili",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. CH.Vasu Naidu",
    username: "INSP_ANANDAPURAM",
    mobileNumber: "7382296908",
    password: "7382296908",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "Anandapuram",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri .CH.Sreedhar",
    username: "INSP_PADMANABHAM",
    mobileNumber: "9490617920",
    password: "9490617920",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "Padmanabham",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Smt. D.Mary Prasanthi, IPS",
    username: "DCP_ZONE2",
    mobileNumber: "9491063502",
    password: "9491063502",
    role: Role.DCP,
    zone: Zone.ZONE_2,
    designation: "D.C.P - L&O - II",
    isActive: true,
  },
  {
    name: "Sri.",
    username: "ACP_HARBOUR",
    mobileNumber: "8331041669",
    password: "8331041669",
    role: Role.ACP,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    designation: "ACP - Harbour",
    isActive: true,
  },
  {
    name: "Sri. CH.Simhadri Naidu",
    username: "INSP_HARBOUR",
    mobileNumber: "9440796013",
    password: "9440796013",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "Harbour",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. P.Vara Prasad",
    username: "INSP_1TOWN",
    mobileNumber: "9440796019",
    password: "9440796019",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "I Town",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. G.Apparao",
    username: "INSP_MALKAPURAM",
    mobileNumber: "9440796023",
    password: "9440796023",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "Malkapuram",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. T.Kameswara Rao",
    username: "INSP_NEWPORT",
    mobileNumber: "9440904309",
    password: "9440904309",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "New Port",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. Y.Srinivasa Rao",
    username: "ACP_SOUTH",
    mobileNumber: "9440796006",
    password: "9440796006",
    role: Role.ACP,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    designation: "ACP - South",
    isActive: true,
  },
  {
    name: "Sri A.Pardha Saradhi",
    username: "INSP_GAJUWAKA",
    mobileNumber: "9440796014",
    password: "9440796014",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Gajuwaka",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. K.Malleswara Rao",
    username: "INSP_DUVVADA",
    mobileNumber: "9440796053",
    password: "9440796053",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Duvvada",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri .E. Kesava Rao",
    username: "INSP_STEELPLANT",
    mobileNumber: "9440796015",
    password: "9440796015",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Steel Plant",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. Prudhvi Teja",
    username: "ACP_WEST",
    mobileNumber: "9440796008",
    password: "9440796008",
    role: Role.ACP,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    designation: "ACP - West",
    isActive: true,
  },
  {
    name: "Sri. K.Ravikumar",
    username: "INSP_KANCHARAPALEM",
    mobileNumber: "9014214742",
    password: "9014214742",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Kancharapalem",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri.V.Sankar Narayana",
    username: "INSP_AIRPORT",
    mobileNumber: "9440904350",
    password: "9440904350",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Airport",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. L.Sanyasi Naidu",
    username: "INSP_GOPALAPATNAM",
    mobileNumber: "9440796020",
    password: "9440796020",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Gopalapatnam",
    designation: "Inspector",
    isActive: true,
  },
  {
    name: "Sri. K.Venkat Satish Kumar",
    username: "INSP_PENDURTHY",
    mobileNumber: "9440796039",
    password: "9440796039",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Pendurthy",
    designation: "Inspector",
    isActive: true,
  },

  // === Crimes Wing ===
  {
    name: "Smt. K.Latha Madhuri",
    username: "DCP_CRIMES",
    mobileNumber: "9490623981",
    password: "9490623981",
    role: Role.DCP,
    designation: "D.C.P - Crimes",
    isActive: true,
  },
  {
    name: "Sri.",
    username: "ADCP_CRIMES",
    mobileNumber: "9490617923",
    password: "9490617923",
    role: Role.DCP,
    designation: "Addl.D.C.P - Crimes",
    isActive: true,
  },
  {
    name: "Sri.",
    username: "ACP_CRIMES1",
    mobileNumber: "9440904321",
    password: "9440904321",
    role: Role.ACP,
    zone: Zone.ZONE_1,
    designation: "ACP - Crimes - 1",
    isActive: true,
  },
  {
    name: "Sri.CH.Rajula Naidu",
    username: "DCI_EAST",
    mobileNumber: "8331041656",
    password: "8331041656",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "East",
    designation: "Detective Chief Inspector",
    isActive: true,
  },
  {
    name: "Sri.CH.Chiranjeevi Rao",
    username: "DSI_IITOWN",
    mobileNumber: "8331041592",
    password: "8331041592",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "II Town",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. K.Krishna",
    username: "DSI_MR-PETA",
    mobileNumber: "9440904331",
    password: "9440904331",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "MR-Peta",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. P.Sankar Rao",
    username: "DSI_IIITOWN",
    mobileNumber: "7989242025",
    password: "7989242025",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "III Town",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. G.Ganapathi Rao",
    username: "DSI_IVTOWN",
    mobileNumber: "7382296913",
    password: "7382296913",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "IV Town",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. V.Chakradhar Rao",
    username: "DCI_DWARAKA",
    mobileNumber: "9490624815",
    password: "9490624815",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "Dwaraka",
    designation: "Detective Chief Inspector",
    isActive: true,
  },
  {
    name: "Sri. L.Srinivasa Rao",
    username: "DSI_DWARAKA",
    mobileNumber: "8331041581",
    password: "8331041581",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "Dwaraka",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. T.Ravi Kumar",
    username: "DSI_MVP",
    mobileNumber: "8331041593",
    password: "8331041593",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "MVP",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. A.Hari Krishna",
    username: "DSI_ARILOVA",
    mobileNumber: "8331041604",
    password: "8331041604",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "Arilova",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.B.Satya Siva Prakash",
    username: "DCI_NORTH",
    mobileNumber: "8331041672",
    password: "8331041672",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "North",
    designation: "Detective Chief Inspector",
    isActive: true,
  },
  {
    name: "Sri. S.Surya Prakash",
    username: "DSI_PMPALEM",
    mobileNumber: "9440904314",
    password: "9440904314",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "PM Palem",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. R.Srinivasu Rao",
    username: "DSI_BHEEMILI",
    mobileNumber: "7382641999",
    password: "7382641999",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "Bheemili",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. SK.Sharief",
    username: "DSI_ANANDAPURAM",
    mobileNumber: "9490624727",
    password: "9490624727",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "Anandapuram",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. G.Venkata Rao",
    username: "DSI_PADMANABHAM",
    mobileNumber: "8331041576",
    password: "8331041576",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "Padmanabham",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.",
    username: "ACP_CRIMES2",
    mobileNumber: "8333997010",
    password: "8333997010",
    role: Role.ACP,
    zone: Zone.ZONE_2,
    designation: "ACP - Crimes - 2",
    isActive: true,
  },
  {
    name: "Sri.G.Srinivas",
    username: "DCI_HARBOUR",
    mobileNumber: "7382296918",
    password: "7382296918",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "Harbour",
    designation: "Detective Chief Inspector",
    isActive: true,
  },
  {
    name: "Sri. P.Prasada Rao",
    username: "DSI_HARBOUR",
    mobileNumber: "8331041578",
    password: "8331041578",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "Harbour",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. P.D.B.Sankar",
    username: "DSI_ITOWN",
    mobileNumber: "9440904310",
    password: "9440904310",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "I Town",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. M.V.Ramana",
    username: "DSI_MALKAPURAM",
    mobileNumber: "9440904329",
    password: "9440904329",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "Malkapuram",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. T.Rukmangadara Rao",
    username: "DSI_NEWPORT",
    mobileNumber: "8331041605",
    password: "8331041605",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "New Port",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.K.Srinivasa Rao",
    username: "DCI_SOUTH",
    mobileNumber: "9490617922",
    password: "9490617922",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "South",
    designation: "Detective Chief Inspector",
    isActive: true,
  },
  {
    name: "Sri. CH.Harikrishna",
    username: "DSI_GAJUWAKA",
    mobileNumber: "9440904339",
    password: "9440904339",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Gajuwaka",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. G.Sattibabu",
    username: "DSI_DUVVADA",
    mobileNumber: "9703117526",
    password: "9703117526",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Duvvada",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. Y.Sambhasiva Rao",
    username: "DSI_STEELPLANT",
    mobileNumber: "9440904328",
    password: "9440904328",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Steel Plant",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. M.Chandra Mouli",
    username: "DCI_WEST",
    mobileNumber: "9440904717",
    password: "9440904717",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "West",
    designation: "Detective Chief Inspector",
    isActive: true,
  },
  {
    name: "SK Abdul Maroff",
    username: "DSI_KANCHARPALEM",
    mobileNumber: "8331041687",
    password: "8331041687",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Kancharapalem",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. K.Ravi Kishore",
    username: "DSI_AIRPORT",
    mobileNumber: "9440904322",
    password: "9440904322",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Airport",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. E.Tejaeswarao Rao",
    username: "DSI_GOPALAPATNAM",
    mobileNumber: "9440904330",
    password: "9440904330",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Gopalapatnam",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. D.Suri Babu",
    username: "DSI_PENDURTHY",
    mobileNumber: "8331041618",
    password: "8331041618",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Pendurthy",
    designation: "Detective Sub-Inspector",
    isActive: true,
  },

  // === Traffic Wing ===
  {
    name: "Sri. K.Praveen Kumar",
    username: "DCP_TRAFFIC",
    mobileNumber: "9440796004",
    password: "9440796004",
    role: Role.DCP,
    designation: "Addl.D.C.P - Traffic",
    isActive: true,
  },
  {
    name: "Sri. S.Vasudev",
    username: "ACP_TRAFFIC1",
    mobileNumber: "9490619450",
    password: "9490619450",
    role: Role.ACP,
    zone: Zone.ZONE_1,
    designation: "ACP - Taffic - 1",
    isActive: true,
  },
  {
    name: "Sri. M.Srinivasu",
    username: "TI_DELTA1",
    mobileNumber: "9440796016",
    password: "9440796016",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "2 Town & MR-Peta",
    designation: "Traffic Inspector - Delta 1",
    isActive: true,
  },
  {
    name: "Sri . N.Simhachalam",
    username: "TSI_IITOWNTRAFFIC",
    mobileNumber: "9440796041",
    password: "9440796041",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "II Town Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. CH.Uma Maheswara Rao",
    username: "TSI_MRPETATRAFFIC",
    mobileNumber: "9492027573",
    password: "9492027573",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "MR Peta Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.S. Ammi Naidu",
    username: "TI_DELTA2",
    mobileNumber: "7382296905",
    password: "7382296905",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "3 Town & 4 Town",
    designation: "Traffic Inspector - Delta 2",
    isActive: true,
  },
  {
    name: "Sri. G.Dhanjaya Naidu",
    username: "TSI_3TOWNTRAFFIC",
    mobileNumber: "9440796042",
    password: "9440796042",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "3Town Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. M.Sudharshan Rao",
    username: "TSI_4THTOWNTRAFFIC",
    mobileNumber: "9440796043",
    password: "9440796043",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    policeStation: "4th Town Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.N.V.Prabhakara Rao",
    username: "TI_DELTA9",
    mobileNumber: "9440904718",
    password: "9440904718",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "DWK, MVP, Arilova",
    designation: "Traffic Inspector - Delta 9",
    isActive: true,
  },
  {
    name: "Sri. T.Ramarao -  RSI",
    username: "TSI_DWARAKATRAFFIC",
    mobileNumber: "9441277516",
    password: "9441277516",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "Dwaraka Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.S. Ramurthy",
    username: "TSI_MVPTRAFFIC",
    mobileNumber: "8121115952",
    password: "8121115952",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "MVP Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. J. Dharmendhar",
    username: "TSI_ARILOVATRAFFIC",
    mobileNumber: "8331041606",
    password: "8331041606",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    policeStation: "Arilova Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.N.Sai",
    username: "TI_DELTA8",
    mobileNumber: "9440904343",
    password: "9440904343",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "PMP, BHM, ANDP, PDM",
    designation: "Traffic Inspector - Delta 8",
    isActive: true,
  },
  {
    name: "Sri. A.Manmadha Rao",
    username: "TSI_PMPALEMTRAFFIC",
    mobileNumber: "9440904316",
    password: "9440904316",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "PM Palem Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. Papa Rao",
    username: "TSI_ANANDAPURAMTRAFFIC",
    mobileNumber: "8331041585",
    password: "8331041585",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "Anandapuram Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.B.Tirupathi Rao  RSI",
    username: "TSI_BHEEMILITRAFFIC",
    mobileNumber: "8106062658",
    password: "8106062658",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    policeStation: "Bheemili Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.",
    username: "ACP_TRAFFIC2",
    mobileNumber: "9440796007",
    password: "9440796007",
    role: Role.ACP,
    zone: Zone.ZONE_2,
    designation: "ACP - Taffic - 2",
    isActive: true,
  },
  {
    name: "Sri.S. Shanmukha Rao",
    username: "TI_DELTA5",
    mobileNumber: "9440796017",
    password: "9440796017",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "1 Town, HBR, MLK, Newport",
    designation: "Traffic Inspector - Delta 5",
    isActive: true,
  },
  {
    name: "Sri. G.Apparao",
    username: "TSI_ITOWNTRAFFIC",
    mobileNumber: "9440796040",
    password: "9440796040",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "I Town Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. G.Vijyakumar  RSI",
    username: "TSI_HARBOURTRAFFIC",
    mobileNumber: "9440796049",
    password: "9440796049",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "Harbour Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. K.Srinivasu Rao",
    username: "TSI_MALKAPURAMTRAFFIC",
    mobileNumber: "9440796045",
    password: "9440796045",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "Malkapuram Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. K.Surya Narayana",
    username: "TSI_NEWPORTTRAFFIC",
    mobileNumber: "9440904333",
    password: "9440904333",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    policeStation: "Newport Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. SK.Hussian",
    username: "TI_DELTA6",
    mobileNumber: "9440796018",
    password: "9440796018",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Gajuwaka",
    designation: "Traffic Inspector - Delta 6",
    isActive: true,
  },
  {
    name: "Sri. M.Radha Krishna",
    username: "TSI_GAJUWAKATRAFFIC",
    mobileNumber: "9440904334",
    password: "9440904334",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Gajuwaka Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.K.Venkata Rao",
    username: "TI_DELTA7",
    mobileNumber: "9440796048",
    password: "9440796048",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Duvvada, Steel Plant",
    designation: "Traffic Inspector - Delta 7",
    isActive: true,
  },
  {
    name: "Sri. S. Lingnna Dora",
    username: "TSI_DUVVADATRAFFIC",
    mobileNumber: "9494147029",
    password: "9494147029",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Duvvada Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. S.B.Sankara Rao",
    username: "TSI_STEELPLANTTRAFFIC",
    mobileNumber: "9440904335",
    password: "9440904335",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    policeStation: "Steelplant Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.A.Dasradhi",
    username: "TI_DELTA3",
    mobileNumber: "9440796037",
    password: "9440796037",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "KCP, Airport",
    designation: "Traffic Inspector - Delta 3",
    isActive: true,
  },
  {
    name: "Sri. SK.Kadharbhasha",
    username: "TSI_KANCHARAPALEMTRAFFIC",
    mobileNumber: "9440796044",
    password: "9440796044",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Kancharapalem Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri.K.Srinivasu Rao",
    username: "TSI_AIRPORTTRAFFIC",
    mobileNumber: "9705503617",
    password: "9705503617",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Airport Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. K.Suresh",
    username: "TI_DELTA4",
    mobileNumber: "9490617919",
    password: "9490617919",
    role: Role.INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "GPT, PDT",
    designation: "Traffic Inspector - Delta 4",
    isActive: true,
  },
  {
    name: "Sri.D.Suribabu",
    username: "TSI_GOPALAPATNAMTRAFFIC",
    mobileNumber: "9440796047",
    password: "9440796047",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Gopalapatnam Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },
  {
    name: "Sri. P.Narsimha Murthy",
    username: "TSI_PENDURTHYTRAFFIC",
    mobileNumber: "9440796064",
    password: "9440796064",
    role: Role.SUB_INSPECTOR,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    policeStation: "Pendurthy Traffic",
    designation: "Traffic Sub-Inspector",
    isActive: true,
  },

  // === Admin / Special Units ===
  {
    name: "Dr. V.B.Rajkamal",
    username: "ADCP_ADMIN",
    mobileNumber: "9440796063",
    password: "9440796063",
    role: Role.DCP,
    designation: "Addl.D.C.P - Admin",
    isActive: true,
  },
  {
    name: "Sri. B.Srinivasa Rao",
    username: "ADCP_CSB",
    mobileNumber: "9440796003",
    password: "9440796003",
    role: Role.DCP,
    designation: "Addl.D.C.P - CSB",
    isActive: true,
  },
  {
    name: "Sri. I.Chitti Babu",
    username: "ACP_CSB",
    mobileNumber: "9440904336",
    password: "9440904336",
    role: Role.ACP,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    designation: "ACP - CSB",
    isActive: true,
  },
  {
    name: "Sri. B.Narayana Rao",
    username: "ADCP_CAR",
    mobileNumber: "9440796027",
    password: "9440796027",
    role: Role.DCP,
    designation: "Addl.D.C.P - CAR",
    isActive: true,
  },
  {
    name: "Sri. S.V.Apparao",
    username: "ACP_CAR1",
    mobileNumber: "9440796009",
    password: "9440796009",
    role: Role.ACP,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    designation: "ACP - CAR - 1",
    isActive: true,
  },
  {
    name: "Sri. Z. Vijaya Kumar",
    username: "ACP_CAR2",
    mobileNumber: "8331041647",
    password: "8331041647",
    role: Role.ACP,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    designation: "ACP - CAR - 2",
    isActive: true,
  },
];
