import { PoliceStation } from '../../police-stations/entities/police-station.entity';
import { Zone } from '../../officers/enums/zone.enum';
import { SubDivision } from '../../officers/enums/sub-division.enum';
import { StationType } from '../../police-stations/enums/station-type.enum';

export const policeStationsSeedData: Partial<PoliceStation>[] = [
  // ==========================================
  // L&O (Law & Order) Police Stations
  // ==========================================
  // ZONE_1 → East Sub-Division
  {
    code: "2038002",
    name: "II Town",
    address: "Two Town, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530002",
    phone: "0891-2564002",
    latitude: 17.6924,
    longitude: 83.2145,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    isActive: true,
    servicePincodes: ["530001", "530002", "530003", "530004", "530011", "530016", "530017", "530020", "530027", "530045"],
  },
  {
    code: "2038091",
    name: "Maharanipeta",
    address: "Maharanipeta, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530002",
    phone: "0891-2564022",
    latitude: 17.6945,
    longitude: 83.2089,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    isActive: true,
    servicePincodes: ["530001", "530002", "530003", "530016", "530045", "531077"],
  },
  {
    code: "2038003",
    name: "III Town",
    address: "Three Town, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530003",
    phone: "0891-2564003",
    latitude: 17.6998,
    longitude: 83.2167,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    isActive: true,
    servicePincodes: ["530001", "530002", "530003", "530013", "530017", "530022", "530023", "530026"],
  },
  {
    code: "2038004",
    name: "IV Town",
    address: "Four Town, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530004",
    phone: "0891-2564004",
    latitude: 17.7052,
    longitude: 83.2298,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    isActive: true,
    servicePincodes: ["530003", "530004", "530013", "530016", "530017", "530024"],
  },

  // ZONE_1 → Dwaraka Sub-Division
  {
    code: "2038076",
    name: "Dwaraka Nagar",
    address: "Dwaraka Nagar, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530016",
    phone: "0891-2564016",
    latitude: 17.7234,
    longitude: 83.3012,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    isActive: true,
    servicePincodes: ["530001", "530003", "530013", "530016", "530017", "535145"],
  },
  {
    code: "2038092",
    name: "Muvvalavanipalem",
    address: "MVP Colony, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530017",
    phone: "0891-2564017",
    latitude: 17.7412,
    longitude: 83.2567,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    isActive: true,
    servicePincodes: ["530013", "530017", "530022", "530040", "530043"],
  },
  {
    code: "2038080",
    name: "Arilova",
    address: "Arilova, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530040",
    phone: "0891-2564040",
    latitude: 17.7634,
    longitude: 83.3412,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    isActive: true,
    servicePincodes: ["530040"],
  },

  // ZONE_1 → North Sub-Division
  {
    code: "2038017",
    name: "PM Palem",
    address: "PM Palem, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530041",
    phone: "0891-2564041",
    latitude: 17.7523,
    longitude: 83.3145,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    isActive: true,
    servicePincodes: ["530013", "530017", "530024", "530041", "530044", "530045", "530048"],
  },
  {
    code: "2038009",
    name: "Bhimunipatnam",
    address: "Bheemili, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "531163",
    phone: "0891-2564163",
    latitude: 17.8845,
    longitude: 83.4278,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    isActive: true,
    servicePincodes: ["530048", "531162", "531163"],
  },
  {
    code: "2038006",
    name: "Anandapuram",
    address: "Anandapuram, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "531173",
    phone: "0891-2564174",
    latitude: 17.8312,
    longitude: 83.3756,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    isActive: true,
    servicePincodes: ["530048", "531162", "531163"],
  },
  {
    code: "2038040",
    name: "Padmanabham",
    address: "Padmanabham, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "531219",
    phone: "0891-2564175",
    latitude: 17.8456,
    longitude: 83.3945,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    isActive: true,
    servicePincodes: ["531219"],
  },

  // ZONE_2 → Harbour Sub-Division
  // Harbour
  {
    code: "VZG-HRB",
    name: "Harbour",
    address: "Visakhapatnam Port Area",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530035",
    phone: "0891-2564035",
    latitude: 17.6789,
    longitude: 83.2867,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    isActive: true,
    servicePincodes: ["530001", "530004", "530005", "530012", "530026"],
  },
  {
    code: "2038001",
    name: "I Town",
    address: "One Town, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530001",
    phone: "0891-2564001",
    latitude: 17.6868,
    longitude: 83.2185,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    isActive: true,
    servicePincodes: ["530001"],
  },
  {
    code: "2038008",
    name: "Malkapuram",
    address: "Malkapuram, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530011",
    phone: "0891-2564011",
    latitude: 17.6712,
    longitude: 83.2345,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    isActive: true,
    servicePincodes: ["530005", "530011", "530012"],
  },
  {
    code: "2038014",
    name: "New Port",
    address: "New Port Area, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530035",
    phone: "0891-2564036",
    latitude: 17.6734,
    longitude: 83.2789,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    isActive: true,
    servicePincodes: ["530005", "530044"],
  },

  // ZONE_2 → South Sub-Division
  {
    code: "2038010",
    name: "Gajuwaka",
    address: "Gajuwaka, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530026",
    phone: "0891-2564026",
    latitude: 17.6534,
    longitude: 83.2012,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    isActive: true,
    servicePincodes: ["530012", "530015", "530026"],
  },
  {
    code: "2038075",
    name: "Duvvada",
    address: "Duvvada, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530046",
    phone: "0891-2564046",
    latitude: 17.6234,
    longitude: 83.1567,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    isActive: true,
    servicePincodes: ["530026", "530046", "531011"],
  },
  {
    code: "VZG-STL",
    name: "Steel Plant",
    address: "Steel Plant Township, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530032",
    phone: "0891-2564032",
    latitude: 17.6312,
    longitude: 83.1567,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    isActive: true,
    servicePincodes: ["530031", "530046"],
  },

  // ZONE_2 → West Sub-Division
  {
    code: "2038042",
    name: "Kancharapalem",
    address: "Kancharapalem, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530008",
    phone: "0891-2564008",
    latitude: 17.7134,
    longitude: 83.2678,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    isActive: true,
    servicePincodes: ["530004", "530007", "530008", "530013", "530024"],
  },
  {
    code: "2038072",
    name: "Airport",
    address: "Airport Road, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530009",
    phone: "0891-2564009",
    latitude: 17.7212,
    longitude: 83.2245,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    isActive: true,
    servicePincodes: ["530009", "530018"],
  },
  {
    code: "2038018",
    name: "Gopalapatnam",
    address: "Gopalapatnam, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530027",
    phone: "0891-2564027",
    latitude: 17.7456,
    longitude: 83.2567,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    isActive: true,
    servicePincodes: ["530027", "530028"],
  },
  {
    code: "2038035",
    name: "Pendurthy",
    address: "Pendurthi, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "531173",
    phone: "0891-2564173",
    latitude: 17.8123,
    longitude: 83.2456,
    type: StationType.LAW_AND_ORDER,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    isActive: true,
    servicePincodes: ["530029", "530047", "530051", "531173"],
  },

  // ==========================================
  // Stations added from the secretariat list (zone/subDivision TBD — fill in later)
  // ==========================================
  // NOTE: Parawada & Sabbavaram fall under Anakapalli District Police
  // (Parawada Sub-Division), which is outside the Visakhapatnam City
  // Zone/SubDivision enums — so zone/subDivision are left null here.
  {
    code: "2038041",
    name: "Parawada",
    address: "Parawada, Anakapalli",
    district: 'Anakapalli',
    city: 'Parawada',
    state: 'Andhra Pradesh',
    pincode: "531019",
    phone: "9440796000",
    type: StationType.LAW_AND_ORDER,
    zone: null,
    subDivision: null,
    isActive: true,
    servicePincodes: ["531019", "531020", "531021"],
  },
  {
    code: "2035012",
    name: "Sabbavaram",
    address: "Sabbavaram, Anakapalli",
    district: 'Anakapalli',
    city: 'Sabbavaram',
    state: 'Andhra Pradesh',
    pincode: "531035",
    phone: "9440796001",
    type: StationType.LAW_AND_ORDER,
    zone: null,
    subDivision: null,
    isActive: true,
    servicePincodes: ["531035"],
  },

  // ==========================================
  // Traffic Police Stations (no servicePincodes — complaints go to L&O)
  // ==========================================
  // ZONE_1 → East Sub-Division
  {
    code: "VZG-02-T",
    name: "II Town Traffic",
    address: "Traffic, Two Town, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530002",
    phone: "0891-2564002",
    latitude: 17.6924,
    longitude: 83.2145,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    isActive: true,
  },
  {
    code: "VZG-MRP-T",
    name: "MR-Peta Traffic",
    address: "Traffic, Maharanipeta, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530002",
    phone: "0891-2564022",
    latitude: 17.6945,
    longitude: 83.2089,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    isActive: true,
  },
  {
    code: "VZG-03-T",
    name: "III Town Traffic",
    address: "Traffic, Three Town, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530003",
    phone: "0891-2564003",
    latitude: 17.6998,
    longitude: 83.2167,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    isActive: true,
  },
  {
    code: "VZG-04-T",
    name: "IV Town Traffic",
    address: "Traffic, Four Town, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530004",
    phone: "0891-2564004",
    latitude: 17.7052,
    longitude: 83.2298,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.EAST,
    isActive: true,
  },

  // ZONE_1 → Dwaraka Sub-Division
  {
    code: "VZG-DWK-T",
    name: "Dwaraka Traffic",
    address: "Traffic, Dwaraka Nagar, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530016",
    phone: "0891-2564016",
    latitude: 17.7234,
    longitude: 83.3012,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    isActive: true,
  },
  {
    code: "VZG-MVP-T",
    name: "MVP Traffic",
    address: "Traffic, MVP Colony, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530017",
    phone: "0891-2564017",
    latitude: 17.7412,
    longitude: 83.2567,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    isActive: true,
  },
  {
    code: "VZG-ARL-T",
    name: "Arilova Traffic",
    address: "Traffic, Arilova, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530040",
    phone: "0891-2564040",
    latitude: 17.7634,
    longitude: 83.3412,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.DWARAKA,
    isActive: true,
  },

  // ZONE_1 → North Sub-Division
  {
    code: "VZG-PMD-T",
    name: "PM Palem Traffic",
    address: "Traffic, PM Palem, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530041",
    phone: "0891-2564041",
    latitude: 17.7523,
    longitude: 83.3145,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    isActive: true,
  },
  {
    code: "VZG-ANP-T",
    name: "Anandapuram Traffic",
    address: "Traffic, Anandapuram, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "531173",
    phone: "0891-2564174",
    latitude: 17.8312,
    longitude: 83.3756,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    isActive: true,
  },
  {
    code: "VZG-BHM-T",
    name: "Bheemili Traffic",
    address: "Traffic, Bheemili, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "531163",
    phone: "0891-2564163",
    latitude: 17.8845,
    longitude: 83.4278,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_1,
    subDivision: SubDivision.NORTH,
    isActive: true,
  },

  // ZONE_2 → Harbour Sub-Division
  {
    code: "VZG-01-T",
    name: "I Town Traffic",
    address: "Traffic, One Town, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530001",
    phone: "0891-2564001",
    latitude: 17.6868,
    longitude: 83.2185,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    isActive: true,
  },
  {
    code: "VZG-HRB-T",
    name: "Harbour Traffic",
    address: "Traffic, Visakhapatnam Port Area",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530035",
    phone: "0891-2564035",
    latitude: 17.6789,
    longitude: 83.2867,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    isActive: true,
  },
  {
    code: "VZG-MLK-T",
    name: "Malkapuram Traffic",
    address: "Traffic, Malkapuram, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530011",
    phone: "0891-2564011",
    latitude: 17.6712,
    longitude: 83.2345,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    isActive: true,
  },
  {
    code: "VZG-NPT-T",
    name: "New Port Traffic",
    address: "Traffic, New Port Area, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530035",
    phone: "0891-2564036",
    latitude: 17.6734,
    longitude: 83.2789,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.HARBOUR,
    isActive: true,
  },

  // ZONE_2 → South Sub-Division
  {
    code: "VZG-GJW-T",
    name: "Gajuwaka Traffic",
    address: "Traffic, Gajuwaka, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530026",
    phone: "0891-2564026",
    latitude: 17.6534,
    longitude: 83.2012,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    isActive: true,
  },
  {
    code: "VZG-DVD-T",
    name: "Duvvada Traffic",
    address: "Traffic, Duvvada, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530046",
    phone: "0891-2564046",
    latitude: 17.6234,
    longitude: 83.1567,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    isActive: true,
  },
  {
    code: "VZG-STL-T",
    name: "Steel Plant Traffic",
    address: "Traffic, Steel Plant Township, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530032",
    phone: "0891-2564032",
    latitude: 17.6312,
    longitude: 83.1567,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.SOUTH,
    isActive: true,
  },

  // ZONE_2 → West Sub-Division
  {
    code: "VZG-KND-T",
    name: "Kancharapalem Traffic",
    address: "Traffic, Kancharapalem, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530008",
    phone: "0891-2564008",
    latitude: 17.7134,
    longitude: 83.2678,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    isActive: true,
  },
  {
    code: "VZG-AIR-T",
    name: "Airport Traffic",
    address: "Traffic, Airport Road, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530009",
    phone: "0891-2564009",
    latitude: 17.7212,
    longitude: 83.2245,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    isActive: true,
  },
  {
    code: "VZG-GPL-T",
    name: "Gopalapatnam Traffic",
    address: "Traffic, Gopalapatnam, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "530027",
    phone: "0891-2564027",
    latitude: 17.7456,
    longitude: 83.2567,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    isActive: true,
  },
  {
    code: "VZG-PND-T",
    name: "Pendurthy Traffic",
    address: "Traffic, Pendurthi, Visakhapatnam",
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: "531173",
    phone: "0891-2564173",
    latitude: 17.8123,
    longitude: 83.2456,
    type: StationType.TRAFFIC,
    zone: Zone.ZONE_2,
    subDivision: SubDivision.WEST,
    isActive: true,
  },
];
