import { PoliceStation } from '../../police-stations/entities/police-station.entity';

export const policeStationsSeedData: Partial<PoliceStation>[] = [
  {
    code: 'VZG-01',
    name: 'I Town Police Station',
    address: 'One Town, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530001',
    phone: '0891-2564001',
    latitude: 17.6868,
    longitude: 83.2185,
    isActive: true,
  },
  {
    code: 'VZG-02',
    name: 'II Town Police Station',
    address: 'Two Town, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530002',
    phone: '0891-2564002',
    latitude: 17.6924,
    longitude: 83.2145,
    isActive: true,
  },
  {
    code: 'VZG-03',
    name: 'III Town Police Station',
    address: 'Three Town, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530003',
    phone: '0891-2564003',
    latitude: 17.6998,
    longitude: 83.2167,
    isActive: true,
  },
  {
    code: 'VZG-04',
    name: 'IV Town Police Station',
    address: 'Four Town, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530004',
    phone: '0891-2564004',
    latitude: 17.7052,
    longitude: 83.2298,
    isActive: true,
  },
  {
    code: 'VZG-DWK',
    name: 'Dwaraka Nagar Police Station',
    address: 'Dwaraka Nagar, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530016',
    phone: '0891-2564016',
    latitude: 17.7234,
    longitude: 83.3012,
    isActive: true,
  },
  {
    code: 'VZG-MVP',
    name: 'MVP Colony Police Station',
    address: 'MVP Colony, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530017',
    phone: '0891-2564017',
    latitude: 17.7412,
    longitude: 83.2567,
    isActive: true,
  },
  {
    code: 'VZG-SEE',
    name: 'Seethammadhara Police Station',
    address: 'Seethammadhara, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530013',
    phone: '0891-2564013',
    latitude: 17.7289,
    longitude: 83.2923,
    isActive: true,
  },
  {
    code: 'VZG-AKK',
    name: 'Akkayyapalem Police Station',
    address: 'Akkayyapalem, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530016',
    phone: '0891-2564018',
    latitude: 17.7156,
    longitude: 83.3234,
    isActive: true,
  },
  {
    code: 'VZG-GJW',
    name: 'Gajuwaka Police Station',
    address: 'Gajuwaka, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530026',
    phone: '0891-2564026',
    latitude: 17.6534,
    longitude: 83.2012,
    isActive: true,
  },
  {
    code: 'VZG-STL',
    name: 'Steel Plant Police Station',
    address: 'Steel Plant Township, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530032',
    phone: '0891-2564032',
    latitude: 17.6312,
    longitude: 83.1567,
    isActive: true,
  },
  {
    code: 'VZG-PDM',
    name: 'Pedagantyada Police Station',
    address: 'Pedagantyada, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530044',
    phone: '0891-2564044',
    latitude: 17.7634,
    longitude: 83.3412,
    isActive: true,
  },
  {
    code: 'VZG-MDP',
    name: 'Madhurawada Police Station',
    address: 'Madhurawada, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530048',
    phone: '0891-2564048',
    latitude: 17.7845,
    longitude: 83.3678,
    isActive: true,
  },
  {
    code: 'VZG-PMD',
    name: 'PM Palem Police Station',
    address: 'PM Palem, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530041',
    phone: '0891-2564041',
    latitude: 17.7523,
    longitude: 83.3145,
    isActive: true,
  },
  {
    code: 'VZG-PND',
    name: 'Pendurthi Police Station',
    address: 'Pendurthi, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '531173',
    phone: '0891-2564173',
    latitude: 17.8123,
    longitude: 83.2456,
    isActive: true,
  },
  {
    code: 'VZG-ANK',
    name: 'Anakapalle Police Station',
    address: 'Anakapalle, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Anakapalle',
    state: 'Andhra Pradesh',
    pincode: '531001',
    phone: '08924-222100',
    latitude: 17.6912,
    longitude: 83.0045,
    isActive: true,
  },
  {
    code: 'VZG-RLW',
    name: 'Railway Police Station',
    address: 'Railway Station, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530004',
    phone: '0891-2746633',
    latitude: 17.7212,
    longitude: 83.2334,
    isActive: true,
  },
  {
    code: 'VZG-HRB',
    name: 'Harbour Police Station',
    address: 'Visakhapatnam Port Area',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530035',
    phone: '0891-2564035',
    latitude: 17.6789,
    longitude: 83.2867,
    isActive: true,
  },
  {
    code: 'VZG-AIR',
    name: 'Airport Police Station',
    address: 'Airport Road, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530009',
    phone: '0891-2564009',
    latitude: 17.7212,
    longitude: 83.2245,
    isActive: true,
  },
  {
    code: 'VZG-KND',
    name: 'Kancharapalem Police Station',
    address: 'Kancharapalem, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530008',
    phone: '0891-2564008',
    latitude: 17.7134,
    longitude: 83.2678,
    isActive: true,
  },
  {
    code: 'VZG-MHL',
    name: 'Maharanipeta Police Station',
    address: 'Maharanipeta, Visakhapatnam',
    district: 'Visakhapatnam',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    pincode: '530002',
    phone: '0891-2564022',
    latitude: 17.6945,
    longitude: 83.2089,
    isActive: true,
  },
];
