export enum ComplaintStatus {
  NEW = 'NEW',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  REJECTED = 'REJECTED',
  RESOLVED = 'RESOLVED',
  CLOSED_WITH_FIR = 'CLOSED_WITH_FIR',
  CLOSED_WITHOUT_FIR = 'CLOSED_WITHOUT_FIR',
}
